import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'
import type { DiagnosisReport, RiskScores } from './types'

export interface PdfDataProps {
  report: DiagnosisReport
  scores: RiskScores
  petName?: string
  generatedAt?: string
}

export function generatePdfDocument(data: PdfDataProps) {
  const { report, scores, petName, generatedAt } = data
  const now = generatedAt || new Date().toLocaleString('ja-JP')

  const styles = StyleSheet.create({
    page: {
      padding: 40,
      fontFamily: 'Helvetica',
      fontSize: 10,
      lineHeight: 1.5,
    },
    header: {
      marginBottom: 20,
      borderBottom: '2 solid #059669',
      paddingBottom: 10,
    },
    title: {
      fontSize: 24,
      fontWeight: 'bold',
      color: '#059669',
      marginBottom: 5,
    },
    subtitle: {
      fontSize: 12,
      color: '#6b7280',
      marginBottom: 10,
    },
    section: {
      marginBottom: 20,
      borderLeft: '3 solid #059669',
      paddingLeft: 15,
    },
    sectionTitle: {
      fontSize: 14,
      fontWeight: 'bold',
      color: '#1f2937',
      marginBottom: 10,
    },
    scoreBox: {
      backgroundColor: '#f0fdf4',
      padding: 10,
      marginBottom: 10,
      borderRadius: 4,
    },
    scoreValue: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#059669',
    },
    scoreLabel: {
      fontSize: 9,
      color: '#6b7280',
    },
    row: {
      flexDirection: 'row',
      marginBottom: 8,
    },
    col: {
      flex: 1,
    },
    riskItem: {
      marginBottom: 8,
      paddingBottom: 8,
      borderBottom: '1 solid #e5e7eb',
    },
    riskTitle: {
      fontWeight: 'bold',
      color: '#1f2937',
      marginBottom: 3,
    },
    riskDetail: {
      fontSize: 9,
      color: '#6b7280',
    },
    footer: {
      marginTop: 40,
      paddingTop: 20,
      borderTop: '1 solid #e5e7eb',
      textAlign: 'center',
      fontSize: 8,
      color: '#9ca3af',
    },
  })

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>ペット防災診断レポート</Text>
          <Text style={styles.subtitle}>{petName || 'あなたのペット'}の防災メソッド</Text>
          <Text style={styles.subtitle}>発行日時: {now}</Text>
        </View>

        {/* 総合スコア */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>総合診断スコア</Text>
          <View style={styles.scoreBox}>
            <Text style={styles.scoreValue}>{scores.overall}/100</Text>
            <Text style={styles.scoreLabel}>{scores.rating}</Text>
          </View>

          <View style={styles.row}>
            <View style={styles.col}>
              <Text style={styles.scoreLabel}>健康リスク</Text>
              <Text style={styles.scoreValue}>{100 - scores.healthRisk}</Text>
            </View>
            <View style={styles.col}>
              <Text style={styles.scoreLabel}>避難難易度</Text>
              <Text style={styles.scoreValue}>{100 - scores.evacuationDifficulty}</Text>
            </View>
            <View style={styles.col}>
              <Text style={styles.scoreLabel}>備蓄充足度</Text>
              <Text style={styles.scoreValue}>{scores.supplyLevel}</Text>
            </View>
          </View>
        </View>

        {/* 総評 */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>診断結果</Text>
          <Text>{report.summary.overallMessage}</Text>
        </View>

        {/* TOP3リスク */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>優先対策 TOP3</Text>
          {report.topRisks.map((risk, i) => (
            <View key={i} style={styles.riskItem}>
              <Text style={styles.riskTitle}>{i + 1}. {risk.title}</Text>
              <Text style={styles.riskDetail}>{risk.detail}</Text>
              <Text style={styles.riskDetail}>対象: {risk.category} | 優先度: {risk.urgency}</Text>
            </View>
          ))}
        </View>

        {/* アクションプラン */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>避難時アクションプラン</Text>
          <View style={styles.riskItem}>
            <Text style={styles.riskTitle}>0〜10分</Text>
            <Text style={styles.riskDetail}>{report.actionPlan.min0_10}</Text>
          </View>
          <View style={styles.riskItem}>
            <Text style={styles.riskTitle}>10〜30分</Text>
            <Text style={styles.riskDetail}>{report.actionPlan.min10_30}</Text>
          </View>
          <View style={styles.riskItem}>
            <Text style={styles.riskTitle}>30〜60分</Text>
            <Text style={styles.riskDetail}>{report.actionPlan.min30_60}</Text>
          </View>
        </View>

        <View style={styles.footer}>
          <Text>© 一般社団法人ペット防災アドバイザー協会</Text>
          <Text>This report was automatically generated by Pet Bousai AI Diagnosis System</Text>
        </View>
      </Page>
    </Document>
  )
}
