// 環境省認定一般家庭用ペット マスターデータ

export type PetType =
  // 哺乳類
  | '犬' | '猫' | 'うさぎ' | 'ハムスター' | 'モルモット'
  | 'チンチラ' | 'デグー' | 'フェレット' | 'リス' | 'ハリネズミ'
  // 鳥類
  | 'セキセイインコ' | 'コザクラインコ' | 'オカメインコ'
  | 'オウム・大型鳥' | '文鳥・カナリア' | 'その他の鳥'
  // 爬虫類
  | 'カメ' | 'トカゲ・ヤモリ' | 'ヘビ'
  // 両生類・魚類
  | '金魚・熱帯魚' | 'カエル・両生類'
  // その他
  | 'その他'

export type ShelterStatus = '○ 可能' | '△ 要確認' | '× 不可'

export interface PetMasterData {
  emoji: string
  category: string
  shelterStatus: ShelterStatus
  shelterNote: string        // 避難所に関する注意
  cannotBringReason?: string // 連れていけない理由
  exerciseNeeds: string      // 運動・活動の必要性
  heatTolerance: '低' | '中' | '高'
  stressSensitivity: '低' | '中' | '高' | '非常に高い'
  shelterRisks: string[]     // 避難所での主なリスク
  commonShelterDiseases: string[] // 避難所環境でかかりやすい病気
  emergencyFood: string      // 避難所の救援物資で代用できるか
  specialFoodNote: string    // 特殊フードの注意点
  amazonSearchUrl: string    // Amazon防災備蓄検索リンク
  minStockDays: number       // 最低備蓄日数（環境省推奨）
}

export const PET_MASTER: Record<PetType, PetMasterData> = {
  '犬': {
    emoji: '🐕',
    category: '哺乳類',
    shelterStatus: '△ 要確認',
    shelterNote: '同行避難可能な避難所は全国の約6割。事前確認が必須。',
    exerciseNeeds: '1日30〜120分の散歩・運動が必要。避難生活では運動不足・ストレスが深刻になりやすい。',
    heatTolerance: '低',
    stressSensitivity: '中',
    shelterRisks: ['他の犬や人へのストレス反応', '吠え声による苦情', 'ケンネルコフ（咳）感染', '運動不足による問題行動'],
    commonShelterDiseases: ['ケンネルコフ（伝染性気管支炎）', '消化器障害（ストレス性下痢）', '皮膚炎（衛生環境悪化）'],
    emergencyFood: '救援物資にドッグフードが含まれる場合あり（種類・量は限定的）',
    specialFoodNote: '療法食・アレルギー対応食・老犬用は救援物資では入手困難。必ず自前で備蓄。',
    amazonSearchUrl: 'https://www.amazon.co.jp/s?k=ドッグフード+非常食+長期保存',
    minStockDays: 7,
  },
  '猫': {
    emoji: '🐈',
    category: '哺乳類',
    shelterStatus: '△ 要確認',
    shelterNote: '猫専用スペースが設けられる避難所は少ない。車中泊・ペットホテル等の代替手段も準備を。',
    exerciseNeeds: '屋内生活が主体だが、避難時はキャリー内での長時間拘束がストレスに。',
    heatTolerance: '中',
    stressSensitivity: '非常に高い',
    shelterRisks: ['環境変化によるストレス性疾患（FIP等）', '隠れ場所がないことによる極度のパニック', '上部気道感染症の蔓延'],
    commonShelterDiseases: ['猫風邪（ヘルペスウイルス・カリシウイルス）', 'ストレス性膀胱炎', '食欲不振・脱水'],
    emergencyFood: '救援物資にキャットフードが含まれる可能性は低い。',
    specialFoodNote: '療法食（腎臓病・泌尿器ケア）は絶対に自前備蓄。一般食への急変は健康悪化を招く。',
    amazonSearchUrl: 'https://www.amazon.co.jp/s?k=キャットフード+長期保存+備蓄',
    minStockDays: 7,
  },
  'うさぎ': {
    emoji: '🐇',
    category: '哺乳類',
    shelterStatus: '△ 要確認',
    shelterNote: '独立したスペースがあれば可能な場合も。騒音・犬猫との接触は命取りになりうる。',
    exerciseNeeds: '1日1〜2時間の運動時間が理想。避難時は最低限のスペース確保を。',
    heatTolerance: '低',
    stressSensitivity: '非常に高い',
    shelterRisks: ['パニックによる心臓発作（興奮死）', '低体温・過熱', '牧草不足による消化器停止（GIスタシス）'],
    commonShelterDiseases: ['GIスタシス（消化管うっ滞）', 'ストレス性食欲不振', 'スナッフル（鼻炎）'],
    emergencyFood: '救援物資でうさぎ用食料は入手不可。牧草・ペレットは必ず自前備蓄。',
    specialFoodNote: '牧草（チモシー）が主食。最低7日分の牧草とペレットを防水袋で保管。',
    amazonSearchUrl: 'https://www.amazon.co.jp/s?k=うさぎ+牧草+備蓄+チモシー',
    minStockDays: 7,
  },
  'ハムスター': {
    emoji: '🐹',
    category: '哺乳類',
    shelterStatus: '△ 要確認',
    shelterNote: '小型ケージで管理しやすいが、温度変化に極めて弱い。15℃以下で擬似冬眠、死亡リスクあり。',
    exerciseNeeds: '回し車での運動が必要。避難時も回し車付きケージを維持。',
    heatTolerance: '低',
    stressSensitivity: '高',
    shelterRisks: ['低体温による擬似冬眠・死亡（15℃以下）', '過熱（28℃以上で熱中症）', 'ストレスによる免疫低下'],
    commonShelterDiseases: ['擬似冬眠（低温環境）', '湿り尻（細菌性腸炎）', '呼吸器感染症'],
    emergencyFood: '救援物資での入手不可。',
    specialFoodNote: 'ペレットフード・ひまわりの種・野菜フレークを1ヶ月分備蓄推奨。',
    amazonSearchUrl: 'https://www.amazon.co.jp/s?k=ハムスター+フード+備蓄',
    minStockDays: 30,
  },
  'モルモット': {
    emoji: '🐾',
    category: '哺乳類',
    shelterStatus: '△ 要確認',
    shelterNote: 'おとなしく他の動物への影響は少ないが、ビタミンC不足が命取りになる。',
    exerciseNeeds: '広めのケージと1日1〜2時間の自由運動を推奨。',
    heatTolerance: '低',
    stressSensitivity: '高',
    shelterRisks: ['ビタミンC欠乏症（壊血病）', '低体温', 'ストレス性食欲不振'],
    commonShelterDiseases: ['壊血病（ビタミンC不足）', '呼吸器疾患', '皮膚炎'],
    emergencyFood: '救援物資での入手不可。',
    specialFoodNote: 'モルモットはビタミンCを自己合成できない。専用ペレット＋ビタミンCサプリを必ず備蓄。',
    amazonSearchUrl: 'https://www.amazon.co.jp/s?k=モルモット+フード+ビタミンC',
    minStockDays: 14,
  },
  'チンチラ': {
    emoji: '🐭',
    category: '哺乳類',
    shelterStatus: '△ 要確認',
    shelterNote: '高温多湿に非常に弱い。28℃以上で熱中症死リスクあり。クーラーボックス＋保冷剤が必須。',
    exerciseNeeds: '1日1〜2時間の運動時間が必要。砂浴びも健康維持に必要。',
    heatTolerance: '低',
    stressSensitivity: '高',
    shelterRisks: ['熱中症（28℃超で致死的）', '高湿度による皮膚・被毛トラブル', 'ストレス性消化器障害'],
    commonShelterDiseases: ['熱中症', '真菌性皮膚炎（高湿度）', 'GIスタシス'],
    emergencyFood: '救援物資での入手不可。',
    specialFoodNote: 'チンチラ専用ペレット・牧草・砂浴び用砂を備蓄。市販の小動物フードは代用不可。',
    amazonSearchUrl: 'https://www.amazon.co.jp/s?k=チンチラ+フード+牧草',
    minStockDays: 14,
  },
  'デグー': {
    emoji: '🐀',
    category: '哺乳類',
    shelterStatus: '△ 要確認',
    shelterNote: '糖分に極めて弱く、一般の小動物フードを与えると糖尿病を発症する危険あり。',
    exerciseNeeds: '回し車での運動と群れでの社会活動が必要。',
    heatTolerance: '低',
    stressSensitivity: '高',
    shelterRisks: ['誤食による糖尿病発症', '低体温', 'ストレス性疾患'],
    commonShelterDiseases: ['糖尿病（甘い食物摂取）', 'GIスタシス', '白内障'],
    emergencyFood: '救援物資での入手不可。砂糖・糖分含有フードは絶対禁止。',
    specialFoodNote: 'デグー専用無糖ペレット必須。他の小動物用フードは与えないこと。',
    amazonSearchUrl: 'https://www.amazon.co.jp/s?k=デグー+フード+無糖',
    minStockDays: 14,
  },
  'フェレット': {
    emoji: '🦦',
    category: '哺乳類',
    shelterStatus: '△ 要確認',
    shelterNote: '臭腺の臭いや活発な行動で他の避難者との摩擦が生じやすい。専用スペース確保が必要。',
    exerciseNeeds: '1日4〜6時間の自由運動が必要。避難時は最低2時間を確保。',
    heatTolerance: '低',
    stressSensitivity: '中',
    shelterRisks: ['熱中症（32℃超で致死的）', 'インスリノーマ（低血糖発作）', 'ストレス性脱毛'],
    commonShelterDiseases: ['インスリノーマ（低血糖）', '副腎疾患', '消化器障害'],
    emergencyFood: '救援物資での入手不可。高タンパク・高脂質フード専用。',
    specialFoodNote: 'フェレット専用フード必須。猫用フードで代用可（緊急時のみ）。インスリノーマの子は補食が必要。',
    amazonSearchUrl: 'https://www.amazon.co.jp/s?k=フェレット+フード+備蓄',
    minStockDays: 7,
  },
  'リス': {
    emoji: '🐿️',
    category: '哺乳類',
    shelterStatus: '△ 要確認',
    shelterNote: '冬季は冬眠するため時期によって対応が異なる。脱走に注意。',
    exerciseNeeds: '広いケージと活発な運動習慣が必要。',
    heatTolerance: '低',
    stressSensitivity: '非常に高い',
    shelterRisks: ['脱走', '不適切な冬眠誘発', 'ストレス死'],
    commonShelterDiseases: ['栄養失調', '骨折（脱走時）', 'ストレス性疾患'],
    emergencyFood: '救援物資での入手不可。',
    specialFoodNote: 'ナッツ類・種子・専用フードを備蓄。防災用に密封容器で保管。',
    amazonSearchUrl: 'https://www.amazon.co.jp/s?k=リス+小動物+フード',
    minStockDays: 14,
  },
  'ハリネズミ': {
    emoji: '🦔',
    category: '哺乳類',
    shelterStatus: '△ 要確認',
    shelterNote: '夜行性のため日中のストレスが大きい。18℃以下で冬眠（低体温症）のリスクあり。',
    exerciseNeeds: '夜間の回し車運動が必要。',
    heatTolerance: '低',
    stressSensitivity: '高',
    shelterRisks: ['低体温による冬眠・死亡', '脱走', 'ストレス性食欲不振'],
    commonShelterDiseases: ['低体温症', '口内炎', '外部寄生虫'],
    emergencyFood: '救援物資での入手不可。',
    specialFoodNote: 'ハリネズミ専用フード必須。昆虫（ミルワーム）も嗜好品として備蓄可。',
    amazonSearchUrl: 'https://www.amazon.co.jp/s?k=ハリネズミ+フード+備蓄',
    minStockDays: 14,
  },
  'セキセイインコ': {
    emoji: '🦜',
    category: '鳥類',
    shelterStatus: '△ 要確認',
    shelterNote: '鳴き声が周囲の迷惑になりやすい。移動用キャリーケージが必須。',
    exerciseNeeds: '1日1〜2時間の放鳥が理想。避難時は困難なため精神的ストレスケアが重要。',
    heatTolerance: '中',
    stressSensitivity: '高',
    shelterRisks: ['ストレスによる免疫低下', '感染症（オウム病等）', '低体温'],
    commonShelterDiseases: ['オウム病（クラミジア）※人にも感染', 'マクロラブダス症', 'ストレス性羽毛損傷'],
    emergencyFood: '救援物資での入手不可。',
    specialFoodNote: '種子・ペレット・青菜を1ヶ月分備蓄。移動用キャリーケージも必須。',
    amazonSearchUrl: 'https://www.amazon.co.jp/s?k=インコ+フード+備蓄+ペレット',
    minStockDays: 30,
  },
  'コザクラインコ': {
    emoji: '🦜',
    category: '鳥類',
    shelterStatus: '△ 要確認',
    shelterNote: '鳴き声が大きいため周囲への配慮が必要。パートナー（番い）と引き離されると深刻なストレスになる。',
    exerciseNeeds: '1日1〜2時間の放鳥が必要。',
    heatTolerance: '中',
    stressSensitivity: '非常に高い',
    shelterRisks: ['パートナー分離によるストレス死', 'オウム病感染', '低体温'],
    commonShelterDiseases: ['オウム病', 'ストレス性羽毛毟り', '呼吸器感染症'],
    emergencyFood: '救援物資での入手不可。',
    specialFoodNote: '種子・ペレット・新鮮な野菜を備蓄。ペアで飼育している場合は2羽分のキャリーを準備。',
    amazonSearchUrl: 'https://www.amazon.co.jp/s?k=コザクラインコ+フード+ペレット',
    minStockDays: 30,
  },
  'オカメインコ': {
    emoji: '🦜',
    category: '鳥類',
    shelterStatus: '△ 要確認',
    shelterNote: '突然の大きな音で「夜間パニック」を起こしやすい。暗くて静かな環境の確保が重要。',
    exerciseNeeds: '1日1〜2時間の放鳥。夜は静かな環境が必須。',
    heatTolerance: '中',
    stressSensitivity: '非常に高い',
    shelterRisks: ['夜間パニック（ナイトフライト）による怪我', '夜間照明によるストレス', 'オウム病感染'],
    commonShelterDiseases: ['オウム病', '呼吸器感染症', 'ストレス性行動異常'],
    emergencyFood: '救援物資での入手不可。',
    specialFoodNote: '種子・ペレット・粟穂を備蓄。夜間カバー（暗幕）も必ず持参。',
    amazonSearchUrl: 'https://www.amazon.co.jp/s?k=オカメインコ+フード+備蓄',
    minStockDays: 30,
  },
  'オウム・大型鳥': {
    emoji: '🦜',
    category: '鳥類',
    shelterStatus: '× 不可',
    shelterNote: '大型鳥類は多くの避難所で受け入れ不可。民間施設・ペットホテル等を事前確保必須。',
    cannotBringReason: '大きな鳴き声（90dB超）・強力な嘴による怪我リスク・ケージの大型化により避難所での管理が困難。オウム病（人畜共通感染症）のリスクも。',
    exerciseNeeds: '1日数時間の放鳥が必要。知的刺激も重要。',
    heatTolerance: '中',
    stressSensitivity: '高',
    shelterRisks: ['大型ケージの搬送困難', 'オウム病の人への感染', '避難所受け入れ拒否'],
    commonShelterDiseases: ['オウム病', '羽毛損傷', 'ストレス性疾患'],
    emergencyFood: '救援物資での入手不可。',
    specialFoodNote: '大型専用ペレット・ナッツ類を十分備蓄。宿泊可能なペットホテルを複数確保しておく。',
    amazonSearchUrl: 'https://www.amazon.co.jp/s?k=オウム+フード+大型鳥+ペレット',
    minStockDays: 30,
  },
  '文鳥・カナリア': {
    emoji: '🐦',
    category: '鳥類',
    shelterStatus: '△ 要確認',
    shelterNote: '小型で管理しやすいが、温度変化と騒音に注意。',
    exerciseNeeds: '1日1時間程度の放鳥が理想。',
    heatTolerance: '中',
    stressSensitivity: '高',
    shelterRisks: ['低体温', '騒音ストレス', '感染症'],
    commonShelterDiseases: ['呼吸器感染症', 'オウム病', 'ストレス性疾患'],
    emergencyFood: '救援物資での入手不可。',
    specialFoodNote: '専用種子・ペレットを備蓄。移動用ケージも必須。',
    amazonSearchUrl: 'https://www.amazon.co.jp/s?k=文鳥+カナリア+フード+備蓄',
    minStockDays: 30,
  },
  'その他の鳥': {
    emoji: '🐦',
    category: '鳥類',
    shelterStatus: '△ 要確認',
    shelterNote: '種類によって避難所受け入れ可否が異なる。事前確認必須。',
    exerciseNeeds: '種類によって異なる。',
    heatTolerance: '中',
    stressSensitivity: '高',
    shelterRisks: ['種類によって異なる', 'オウム病等人畜共通感染症リスク'],
    commonShelterDiseases: ['オウム病', '呼吸器感染症'],
    emergencyFood: '救援物資での入手不可。',
    specialFoodNote: '専用フードを十分備蓄。種類ごとの必要量を事前に確認。',
    amazonSearchUrl: 'https://www.amazon.co.jp/s?k=鳥+フード+備蓄',
    minStockDays: 30,
  },
  'カメ': {
    emoji: '🐢',
    category: '爬虫類',
    shelterStatus: '△ 要確認',
    shelterNote: '水棲ガメは水槽の搬送が困難。陸棲ガメは比較的管理しやすい。温度管理が重要。',
    exerciseNeeds: '陸棲ガメは散歩程度。水棲ガメは水槽サイズが重要。',
    heatTolerance: '高',
    stressSensitivity: '低',
    shelterRisks: ['低体温による代謝停止', '水棲ガメの水槽搬送困難', 'UVB照射不足'],
    commonShelterDiseases: ['肺炎（低体温）', 'ビタミンD欠乏（UVB不足）', 'サルモネラ菌感染（人への感染注意）'],
    emergencyFood: '救援物資での入手不可。',
    specialFoodNote: 'カメ専用フード・カルシウム剤・UVBランプ（電池式）を備蓄。サルモネラ菌対策として手洗い徹底。',
    amazonSearchUrl: 'https://www.amazon.co.jp/s?k=カメ+爬虫類+フード+備蓄+UVB',
    minStockDays: 14,
  },
  'トカゲ・ヤモリ': {
    emoji: '🦎',
    category: '爬虫類',
    shelterStatus: '△ 要確認',
    shelterNote: '多くの避難所で受け入れ困難。温度・湿度管理が命綱。断熱容器＋カイロが必須。',
    exerciseNeeds: '種類によって異なるが、適切なケージサイズと温度勾配が必要。',
    heatTolerance: '高',
    stressSensitivity: '中',
    shelterRisks: ['低体温による消化停止・死亡', 'UVB照射不足（フトアゴ等）', '脱水'],
    commonShelterDiseases: ['肺炎（低体温）', 'MBD（代謝性骨疾患）', 'ストレス性食欲不振'],
    emergencyFood: '救援物資での入手不可。昆虫食種は生き餌の確保が課題。',
    specialFoodNote: 'フリーズドライの昆虫（コオロギ等）・専用フードを1ヶ月分備蓄。カルシウムパウダー必須。',
    amazonSearchUrl: 'https://www.amazon.co.jp/s?k=爬虫類+フード+コオロギ+備蓄',
    minStockDays: 30,
  },
  'ヘビ': {
    emoji: '🐍',
    category: '爬虫類',
    shelterStatus: '× 不可',
    shelterNote: '全国ほぼすべての避難所で受け入れ不可。民間施設の事前確保が絶対に必要。',
    cannotBringReason: '他の避難者への恐怖・パニック誘発のリスクが極めて高い。脱走した場合の被害が甚大。毒ヘビかどうかにかかわらず受け入れ拒否が一般的。緊急時は自宅の安全な部屋に隔離し、後から回収するケースも。',
    exerciseNeeds: 'ケージ内での生活が主体。',
    heatTolerance: '高',
    stressSensitivity: '低',
    shelterRisks: ['避難所受け入れ拒否', '低体温による代謝停止', '脱走による二次被害'],
    commonShelterDiseases: ['肺炎（低体温）', '口腔炎', '皮膚感染症'],
    emergencyFood: '救援物資での入手不可。冷凍マウス等の確保が課題。',
    specialFoodNote: '冷凍マウス・ラットを1ヶ月分以上冷凍保存。停電時の解凍方法も事前に検討。',
    amazonSearchUrl: 'https://www.amazon.co.jp/s?k=ヘビ+爬虫類+飼育+保温',
    minStockDays: 30,
  },
  '金魚・熱帯魚': {
    emoji: '🐠',
    category: '魚類・両生類',
    shelterStatus: '× 不可',
    shelterNote: '水槽ごとの搬送は現実的に不可能。大きな災害では諦める判断も必要。小型の緊急用エアポンプ・バッテリーの準備を。',
    cannotBringReason: '重い水槽の搬送が困難で、避難所に水槽設置スペースがない。酸素供給・温度管理が途絶えると数時間で死亡するため、同行避難はほぼ不可能。',
    exerciseNeeds: '水槽のサイズと水質管理が重要。',
    heatTolerance: '中',
    stressSensitivity: '中',
    shelterRisks: ['停電による酸素供給停止', '水温変化による死亡', '水槽搬送不可'],
    commonShelterDiseases: ['白点病（ストレス・水温変化）', '水カビ病', '細菌感染症'],
    emergencyFood: '救援物資での入手不可。',
    specialFoodNote: 'フレーク状フード2〜4週間分＋バッテリー式エアポンプを備蓄。停電時の水温維持も検討。',
    amazonSearchUrl: 'https://www.amazon.co.jp/s?k=熱帯魚+金魚+フード+備蓄+停電対策',
    minStockDays: 14,
  },
  'カエル・両生類': {
    emoji: '🐸',
    category: '魚類・両生類',
    shelterStatus: '× 不可',
    shelterNote: 'ほとんどの避難所で受け入れ不可。湿度・温度管理が命綱で、避難所環境では維持困難。',
    cannotBringReason: '両生類は皮膚呼吸のため乾燥に極めて弱く、避難所の乾燥した環境では短時間で死亡。また、サルモネラ菌等の感染リスクを避難所管理者が懸念する。',
    exerciseNeeds: '適切な湿度（70〜90%）と温度管理が最優先。',
    heatTolerance: '中',
    stressSensitivity: '高',
    shelterRisks: ['乾燥による皮膚呼吸困難・死亡', '温度変化による代謝停止', 'サルモネラ菌感染（人への感染）'],
    commonShelterDiseases: ['乾燥症', 'ツボカビ症', '細菌性皮膚感染'],
    emergencyFood: '救援物資での入手不可。冷凍コオロギ等の確保が課題。',
    specialFoodNote: 'フリーズドライコオロギ・専用フードと、霧吹き・保湿材を備蓄。',
    amazonSearchUrl: 'https://www.amazon.co.jp/s?k=両生類+カエル+フード+コオロギ',
    minStockDays: 14,
  },
  'その他': {
    emoji: '🐾',
    category: 'その他',
    shelterStatus: '△ 要確認',
    shelterNote: '種類によって避難所可否が大きく異なる。事前に市区町村の避難所担当者に確認必須。',
    exerciseNeeds: '種類によって異なる。',
    heatTolerance: '中',
    stressSensitivity: '中',
    shelterRisks: ['種類によって異なる'],
    commonShelterDiseases: ['種類によって異なる'],
    emergencyFood: '救援物資での入手は困難な場合が多い。',
    specialFoodNote: '種類ごとの専用フードを最低7日〜1ヶ月分備蓄。',
    amazonSearchUrl: 'https://www.amazon.co.jp/s?k=ペット+フード+非常食+備蓄',
    minStockDays: 7,
  },
}

// 避難所に連れていけないペット一覧
export const CANNOT_BRING_PETS = Object.entries(PET_MASTER)
  .filter(([, v]) => v.shelterStatus === '× 不可')
  .map(([k, v]) => ({ type: k as PetType, ...v }))
